// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    event_id, node_id, severity, source, summary, detected_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note
`

type CreateIncidentParams struct {
	EventID    pgtype.UUID        `json:"event_id"`
	NodeID     pgtype.UUID        `json:"node_id"`
	Severity   string             `json:"severity"`
	Source     string             `json:"source"`
	Summary    string             `json:"summary"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
}

// Records a new incident detected by a node.
func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.EventID,
		arg.NodeID,
		arg.Severity,
		arg.Source,
		arg.Summary,
		arg.DetectedAt,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NodeID,
		&i.Severity,
		&i.Source,
		&i.Summary,
		&i.Status,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const filterIncidents = `-- name: FilterIncidents :many
SELECT id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note FROM incidents
WHERE
    ($1::text   = '' OR severity = $1::text)
    AND ($2::text = '' OR status::text = $2::text)
    AND ($3::text = '' OR source = $3::text)
    AND ($4::timestamptz IS NULL
         OR detected_at >= $4::timestamptz)
    AND ($5::timestamptz IS NULL
         OR detected_at <= $5::timestamptz)
    AND ($6::text = ''
         OR summary ILIKE '%' || $6::text || '%')
ORDER BY detected_at DESC
`

type FilterIncidentsParams struct {
	Severity string             `json:"severity"`
	Status   string             `json:"status"`
	Source   string             `json:"source"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	Search   string             `json:"search"`
}

// Lists incidents matching optional filters. An empty/zero filter
// argument disables that filter. The time window is an optional
// [from, to] range; either bound may be null. Newest first.
func (q *Queries) FilterIncidents(ctx context.Context, arg FilterIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, filterIncidents,
		arg.Severity,
		arg.Status,
		arg.Source,
		arg.FromTime,
		arg.ToTime,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.NodeID,
			&i.Severity,
			&i.Source,
			&i.Summary,
			&i.Status,
			&i.DetectedAt,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncident = `-- name: GetIncident :one
SELECT id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note FROM incidents
WHERE id = $1
`

// Fetches a single incident by its ID.
func (q *Queries) GetIncident(ctx context.Context, id pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NodeID,
		&i.Severity,
		&i.Source,
		&i.Summary,
		&i.Status,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const listApprovedIncidentsByNode = `-- name: ListApprovedIncidentsByNode :many
SELECT id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note FROM incidents
WHERE node_id = $1 AND status = 'approved'
ORDER BY decided_at ASC
`

// Lists incidents approved and awaiting execution for a given node,
// oldest first so they are executed in the order they were approved.
func (q *Queries) ListApprovedIncidentsByNode(ctx context.Context, nodeID pgtype.UUID) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listApprovedIncidentsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.NodeID,
			&i.Severity,
			&i.Source,
			&i.Summary,
			&i.Status,
			&i.DetectedAt,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note FROM incidents
ORDER BY detected_at DESC
`

// Lists all incidents, newest first. Used by the dashboard.
func (q *Queries) ListIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.NodeID,
			&i.Severity,
			&i.Source,
			&i.Summary,
			&i.Status,
			&i.DetectedAt,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByStatus = `-- name: ListIncidentsByStatus :many
SELECT id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note FROM incidents
WHERE status = $1
ORDER BY detected_at DESC
`

// Lists incidents in a given lifecycle state, newest first.
func (q *Queries) ListIncidentsByStatus(ctx context.Context, status IncidentStatus) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.NodeID,
			&i.Severity,
			&i.Source,
			&i.Summary,
			&i.Status,
			&i.DetectedAt,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentDecision = `-- name: UpdateIncidentDecision :one
UPDATE incidents
SET status = $2,
    decided_by = $3,
    decided_at = now(),
    decision_note = $4
WHERE id = $1
RETURNING id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note
`

type UpdateIncidentDecisionParams struct {
	ID           pgtype.UUID    `json:"id"`
	Status       IncidentStatus `json:"status"`
	DecidedBy    *string        `json:"decided_by"`
	DecisionNote *string        `json:"decision_note"`
}

// Records an operator's approve/reject decision on an incident.
func (q *Queries) UpdateIncidentDecision(ctx context.Context, arg UpdateIncidentDecisionParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentDecision,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionNote,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NodeID,
		&i.Severity,
		&i.Source,
		&i.Summary,
		&i.Status,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
SET status = $1
WHERE id = $2
RETURNING id, event_id, node_id, severity, source, summary, status, detected_at, created_at, decided_by, decided_at, decision_note
`

type UpdateIncidentStatusParams struct {
	Status IncidentStatus `json:"status"`
	ID     pgtype.UUID    `json:"id"`
}

// Updates only the lifecycle status (e.g. to 'executed' or 'failed').
func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus, arg.Status, arg.ID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NodeID,
		&i.Severity,
		&i.Source,
		&i.Summary,
		&i.Status,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}
