// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IncidentStatus string

const (
	IncidentStatusPendingReview IncidentStatus = "pending_review"
	IncidentStatusApproved      IncidentStatus = "approved"
	IncidentStatusRejected      IncidentStatus = "rejected"
	IncidentStatusExecuted      IncidentStatus = "executed"
	IncidentStatusFailed        IncidentStatus = "failed"
)

func (e *IncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentStatus(s)
	case string:
		*e = IncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentStatus: %T", src)
	}
	return nil
}

type NullIncidentStatus struct {
	IncidentStatus IncidentStatus `json:"incident_status"`
	Valid          bool           `json:"valid"` // Valid is true if IncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentStatus), nil
}

type PolicyVerdict string

const (
	PolicyVerdictApproved    PolicyVerdict = "approved"
	PolicyVerdictNeedsReview PolicyVerdict = "needs_review"
	PolicyVerdictBlocked     PolicyVerdict = "blocked"
)

func (e *PolicyVerdict) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PolicyVerdict(s)
	case string:
		*e = PolicyVerdict(s)
	default:
		return fmt.Errorf("unsupported scan type for PolicyVerdict: %T", src)
	}
	return nil
}

type NullPolicyVerdict struct {
	PolicyVerdict PolicyVerdict `json:"policy_verdict"`
	Valid         bool          `json:"valid"` // Valid is true if PolicyVerdict is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPolicyVerdict) Scan(value interface{}) error {
	if value == nil {
		ns.PolicyVerdict, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PolicyVerdict.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPolicyVerdict) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PolicyVerdict), nil
}

type Command struct {
	ID              pgtype.UUID `json:"id"`
	PlanID          pgtype.UUID `json:"plan_id"`
	CommandOrder    int32       `json:"command_order"`
	CommandText     string      `json:"command_text"`
	Explanation     string      `json:"explanation"`
	RollbackCommand string      `json:"rollback_command"`
}

type Incident struct {
	ID           pgtype.UUID        `json:"id"`
	EventID      pgtype.UUID        `json:"event_id"`
	NodeID       pgtype.UUID        `json:"node_id"`
	Severity     string             `json:"severity"`
	Source       string             `json:"source"`
	Summary      string             `json:"summary"`
	Status       IncidentStatus     `json:"status"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DecidedBy    *string            `json:"decided_by"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	DecisionNote *string            `json:"decision_note"`
}

type Plan struct {
	ID          pgtype.UUID        `json:"id"`
	IncidentID  pgtype.UUID        `json:"incident_id"`
	RootCause   string             `json:"root_cause"`
	RiskLevel   string             `json:"risk_level"`
	Confidence  float64            `json:"confidence"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PolicyDecision struct {
	ID        pgtype.UUID        `json:"id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	Verdict   PolicyVerdict      `json:"verdict"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
}

type PolicyFinding struct {
	ID           pgtype.UUID `json:"id"`
	DecisionID   pgtype.UUID `json:"decision_id"`
	CommandOrder int32       `json:"command_order"`
	CommandText  string      `json:"command_text"`
	RuleID       string      `json:"rule_id"`
	Action       string      `json:"action"`
	Description  string      `json:"description"`
}
