// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommand = `-- name: CreateCommand :one
INSERT INTO commands (
    plan_id, command_order, command_text, explanation, rollback_command
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, plan_id, command_order, command_text, explanation, rollback_command
`

type CreateCommandParams struct {
	PlanID          pgtype.UUID `json:"plan_id"`
	CommandOrder    int32       `json:"command_order"`
	CommandText     string      `json:"command_text"`
	Explanation     string      `json:"explanation"`
	RollbackCommand string      `json:"rollback_command"`
}

// Stores a single command of a plan.
func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, createCommand,
		arg.PlanID,
		arg.CommandOrder,
		arg.CommandText,
		arg.Explanation,
		arg.RollbackCommand,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.CommandOrder,
		&i.CommandText,
		&i.Explanation,
		&i.RollbackCommand,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    incident_id, root_cause, risk_level, confidence, generated_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, incident_id, root_cause, risk_level, confidence, generated_at, created_at
`

type CreatePlanParams struct {
	IncidentID  pgtype.UUID        `json:"incident_id"`
	RootCause   string             `json:"root_cause"`
	RiskLevel   string             `json:"risk_level"`
	Confidence  float64            `json:"confidence"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

// Stores the remediation plan generated for an incident.
func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.IncidentID,
		arg.RootCause,
		arg.RiskLevel,
		arg.Confidence,
		arg.GeneratedAt,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.RootCause,
		&i.RiskLevel,
		&i.Confidence,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByIncident = `-- name: GetPlanByIncident :one
SELECT id, incident_id, root_cause, risk_level, confidence, generated_at, created_at FROM plans
WHERE incident_id = $1
`

// Fetches the plan belonging to a given incident.
func (q *Queries) GetPlanByIncident(ctx context.Context, incidentID pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByIncident, incidentID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.RootCause,
		&i.RiskLevel,
		&i.Confidence,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCommandsByPlan = `-- name: ListCommandsByPlan :many
SELECT id, plan_id, command_order, command_text, explanation, rollback_command FROM commands
WHERE plan_id = $1
ORDER BY command_order ASC
`

// Lists the commands of a plan, in execution order.
func (q *Queries) ListCommandsByPlan(ctx context.Context, planID pgtype.UUID) ([]Command, error) {
	rows, err := q.db.Query(ctx, listCommandsByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.CommandOrder,
			&i.CommandText,
			&i.Explanation,
			&i.RollbackCommand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
