// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyDecision = `-- name: CreatePolicyDecision :one
INSERT INTO policy_decisions (
    plan_id, verdict
) VALUES (
    $1, $2
)
RETURNING id, plan_id, verdict, decided_at
`

type CreatePolicyDecisionParams struct {
	PlanID  pgtype.UUID   `json:"plan_id"`
	Verdict PolicyVerdict `json:"verdict"`
}

// Stores the policy engine's verdict for a plan.
func (q *Queries) CreatePolicyDecision(ctx context.Context, arg CreatePolicyDecisionParams) (PolicyDecision, error) {
	row := q.db.QueryRow(ctx, createPolicyDecision, arg.PlanID, arg.Verdict)
	var i PolicyDecision
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Verdict,
		&i.DecidedAt,
	)
	return i, err
}

const createPolicyFinding = `-- name: CreatePolicyFinding :one
INSERT INTO policy_findings (
    decision_id, command_order, command_text, rule_id, action, description
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, decision_id, command_order, command_text, rule_id, action, description
`

type CreatePolicyFindingParams struct {
	DecisionID   pgtype.UUID `json:"decision_id"`
	CommandOrder int32       `json:"command_order"`
	CommandText  string      `json:"command_text"`
	RuleID       string      `json:"rule_id"`
	Action       string      `json:"action"`
	Description  string      `json:"description"`
}

// Stores a single finding of a policy decision.
func (q *Queries) CreatePolicyFinding(ctx context.Context, arg CreatePolicyFindingParams) (PolicyFinding, error) {
	row := q.db.QueryRow(ctx, createPolicyFinding,
		arg.DecisionID,
		arg.CommandOrder,
		arg.CommandText,
		arg.RuleID,
		arg.Action,
		arg.Description,
	)
	var i PolicyFinding
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.CommandOrder,
		&i.CommandText,
		&i.RuleID,
		&i.Action,
		&i.Description,
	)
	return i, err
}

const getPolicyDecisionByPlan = `-- name: GetPolicyDecisionByPlan :one
SELECT id, plan_id, verdict, decided_at FROM policy_decisions
WHERE plan_id = $1
`

// Fetches the policy decision belonging to a given plan.
func (q *Queries) GetPolicyDecisionByPlan(ctx context.Context, planID pgtype.UUID) (PolicyDecision, error) {
	row := q.db.QueryRow(ctx, getPolicyDecisionByPlan, planID)
	var i PolicyDecision
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Verdict,
		&i.DecidedAt,
	)
	return i, err
}

const listFindingsByDecision = `-- name: ListFindingsByDecision :many
SELECT id, decision_id, command_order, command_text, rule_id, action, description FROM policy_findings
WHERE decision_id = $1
ORDER BY command_order ASC
`

// Lists the findings of a policy decision, in command order.
func (q *Queries) ListFindingsByDecision(ctx context.Context, decisionID pgtype.UUID) ([]PolicyFinding, error) {
	rows, err := q.db.Query(ctx, listFindingsByDecision, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyFinding
	for rows.Next() {
		var i PolicyFinding
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.CommandOrder,
			&i.CommandText,
			&i.RuleID,
			&i.Action,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
