-- Sentinel initial schema.
-- The lifecycle of one anomaly: incident -> plan -> commands + decision.

-- Lifecycle state of an incident. Enforced by the database itself.
CREATE TYPE incident_status AS ENUM (
    'pending_review',  -- awaiting an operator decision
    'approved',        -- operator approved the plan
    'rejected',        -- operator rejected the plan
    'executed',        -- the approved plan ran successfully
    'failed'           -- the approved plan ran but failed
);

-- Overall verdict of the policy engine for a plan.
CREATE TYPE policy_verdict AS ENUM (
    'approved',
    'needs_review',
    'blocked'
);

-- An incident: the full record of one detected anomaly.
CREATE TABLE incidents (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id        UUID NOT NULL,
    node_id         UUID NOT NULL,
    severity        TEXT NOT NULL,
    source          TEXT NOT NULL,
    summary         TEXT NOT NULL,
    status          incident_status NOT NULL DEFAULT 'pending_review',
    detected_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Operator decision tracking (filled when reviewed).
    decided_by      TEXT,
    decided_at      TIMESTAMPTZ,
    decision_note   TEXT
);

-- A remediation plan generated by the reasoning engine for an incident.
CREATE TABLE plans (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_id     UUID NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    root_cause      TEXT NOT NULL,
    risk_level      TEXT NOT NULL,
    confidence      DOUBLE PRECISION NOT NULL,
    generated_at    TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A single command within a plan. A plan has many commands.
CREATE TABLE commands (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id             UUID NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
    command_order       INTEGER NOT NULL,
    command_text        TEXT NOT NULL,
    explanation         TEXT NOT NULL,
    rollback_command    TEXT NOT NULL DEFAULT ''
);

-- The policy engine's decision for a plan.
CREATE TABLE policy_decisions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id         UUID NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
    verdict         policy_verdict NOT NULL,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A single finding within a policy decision: why one command was judged.
CREATE TABLE policy_findings (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    decision_id         UUID NOT NULL REFERENCES policy_decisions(id) ON DELETE CASCADE,
    command_order       INTEGER NOT NULL,
    command_text        TEXT NOT NULL,
    rule_id             TEXT NOT NULL DEFAULT '',
    action              TEXT NOT NULL,
    description         TEXT NOT NULL
);

-- Indexes for the queries the dashboard will run most often.
CREATE INDEX idx_incidents_status ON incidents(status);
CREATE INDEX idx_incidents_detected_at ON incidents(detected_at DESC);
CREATE INDEX idx_plans_incident_id ON plans(incident_id);
CREATE INDEX idx_commands_plan_id ON commands(plan_id);
CREATE INDEX idx_policy_decisions_plan_id ON policy_decisions(plan_id);
CREATE INDEX idx_policy_findings_decision_id ON policy_findings(decision_id);